/**
 * modalStyles.js — gedeelde inline stijlen voor alle modals
 */
export const modalStyles = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.45)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  dialog: {
    background: '#fff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    width: '480px',
    maxWidth: '95vw',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  dialogWide: {
    background: '#fff',
    borderRadius: '12px',
    border: '1px solid #e2e8f0',
    width: '680px',
    maxWidth: '95vw',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  dialogHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 1.25rem',
    borderBottom: '1px solid #e2e8f0',
    flexShrink: 0,
  },
  dialogTitle: {
    fontWeight: 900,
    fontSize: '1rem',
    color: '#1e293b',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: '#94a3b8',
    padding: '2px',
    display: 'flex',
    alignItems: 'center',
  },
  body: {
    padding: '1.25rem',
    overflowY: 'auto',
    flex: 1,
  },
  footer: {
    display: 'flex',
    gap: '0.75rem',
    padding: '1rem 1.25rem',
    borderTop: '1px solid #e2e8f0',
    justifyContent: 'flex-end',
    flexShrink: 0,
  },
  label: {
    display: 'block',
    fontSize: '0.75rem',
    fontWeight: 700,
    color: '#475569',
    marginBottom: '4px',
  },
  input: {
    width: '100%',
    padding: '0.55rem 0.75rem',
    marginBottom: '1rem',
    borderRadius: '6px',
    border: '1px solid #cbd5e1',
    fontSize: '0.875rem',
    boxSizing: 'border-box',
    outline: 'none',
  },
  btnPrimary: {
    background: '#2563eb',
    color: '#fff',
    border: 'none',
    padding: '0.55rem 1.25rem',
    borderRadius: '6px',
    fontWeight: 700,
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  btnSecondary: {
    background: '#fff',
    color: '#475569',
    border: '1px solid #cbd5e1',
    padding: '0.55rem 1.25rem',
    borderRadius: '6px',
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  btnDanger: {
    background: '#ef4444',
    color: '#fff',
    border: 'none',
    padding: '0.55rem 1.25rem',
    borderRadius: '6px',
    fontWeight: 700,
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  errorMsg: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#991b1b',
    borderRadius: '6px',
    padding: '0.6rem 0.75rem',
    fontSize: '0.8rem',
    marginTop: '0.25rem',
  },
};
