/**
 * modalStyles.js — gedeelde inline stijlen voor alle modals
 */
import { color, radius, shadow } from '../../../theme';

export const modalStyles = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(15,23,42,0.55)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  dialog: {
    background: color.surface,
    borderRadius: radius.lg,
    border: `1px solid ${color.border}`,
    boxShadow: shadow.lg,
    width: '480px',
    maxWidth: '95vw',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  dialogWide: {
    background: color.surface,
    borderRadius: radius.lg,
    border: `1px solid ${color.border}`,
    boxShadow: shadow.lg,
    width: '680px',
    maxWidth: '95vw',
    maxHeight: '90vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  dialogHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 1.25rem',
    borderBottom: `1px solid ${color.border}`,
    flexShrink: 0,
  },
  dialogTitle: {
    fontWeight: 900,
    fontSize: '1rem',
    color: color.inkSoft,
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: color.faint,
    padding: '2px',
    display: 'flex',
    alignItems: 'center',
  },
  body: {
    padding: '1.25rem',
    overflowY: 'auto',
    flex: 1,
  },
  footer: {
    display: 'flex',
    gap: '0.75rem',
    padding: '1rem 1.25rem',
    borderTop: `1px solid ${color.border}`,
    justifyContent: 'flex-end',
    flexShrink: 0,
  },
  label: {
    display: 'block',
    fontSize: '0.75rem',
    fontWeight: 700,
    color: color.body,
    marginBottom: '4px',
  },
  input: {
    width: '100%',
    padding: '0.55rem 0.75rem',
    marginBottom: '1rem',
    borderRadius: '6px',
    border: `1px solid ${color.faintest}`,
    fontSize: '0.875rem',
    color: color.ink,
    boxSizing: 'border-box',
    outline: 'none',
  },
  btnPrimary: {
    background: color.primary,
    color: '#fff',
    border: 'none',
    padding: '0.55rem 1.25rem',
    borderRadius: '6px',
    fontWeight: 700,
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  btnSecondary: {
    background: color.surface,
    color: color.body,
    border: `1px solid ${color.faintest}`,
    padding: '0.55rem 1.25rem',
    borderRadius: '6px',
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  btnDanger: {
    background: color.danger,
    color: '#fff',
    border: 'none',
    padding: '0.55rem 1.25rem',
    borderRadius: '6px',
    fontWeight: 700,
    fontSize: '0.875rem',
    cursor: 'pointer',
  },
  errorMsg: {
    background: color.dangerSoft,
    border: `1px solid ${color.dangerBorder}`,
    color: '#991b1b',
    borderRadius: '6px',
    padding: '0.6rem 0.75rem',
    fontSize: '0.8rem',
    marginTop: '0.25rem',
  },
};
